### ISSUE TITLE
Add archived version to releases?

### ISSUE THREAD

**Issue by vinkla** [yoshuawuyts/vmd#24]
Would be awesome if you guys added an archive to the releases so we wont have to download and run npm ourselfs. What do you think?

**Comment by maxkueng** [comment]
There is [electron-packager](https://www.npmjs.com/package/electron-packager) which can be used to make builds. Mapbox Studio's [build scripts](https://github.com/mapbox/mapbox-studio/tree/mb-pages/scripts) could be used for inspiration too. They create an NSIS installer for Windows (but it requires building on Windows).

**Comment by yoshuawuyts** [comment]
Neat idea! Took a first shot at it in https://github.com/yoshuawuyts/vmd/pull/25. Build seems to work, haven't tested the release though. Also linux doesn't seem to compile on my machine for some reason. Let me know what you guys think.

**Comment by vinkla** [comment]
Here is apps that does this [Playback](https://github.com/mafintosh/playback/releases), [Imagemin](https://github.com/imagemin/imagemin-app/releases) and [Gulp](https://github.com/sindresorhus/gulp-app/releases).

**Comment by yoshuawuyts** [comment]
Yeah, I saw playback but it's still using the `3.x.x` branch of `electron-packager`. The other two modules use different packaging systems, so it's hard to find overlapping parts in there.

**Comment by vinkla** [comment]
This issue is fairly old, closing it due to inactivity.

**Comment by maxkueng** [comment]
Fixed in c7db898. I've released [version 1.26.2](https://github.com/yoshuawuyts/vmd/releases/tag/1.26.2) with prebuilt archives in .zip and .tar.gz.

The mac and win32 builds are not signed and I haven't tested them. It's possible that the mac build will not work depending the operating system security systems. I think modern OS X will refuse to run unsigned apps. On Windows there might just be a warning that the app is from an "unknown" developer/publisher.

I don't have Windows or OS X so I can't sign the app. And there seems to be no solution to do this on Linux, and I couldn't find a cloud-based solution (like CI for code signing).

I'm closing this issue because technically there are archives now. If you experience problems with one of the releases please create separate issues for the specific archives (i.e. for the platform).

It'd be cool if you could try out the archived releases. Also, if you know of a solution to do automated code signing for mac and/or windows apps on Linux or in the cloud I'd be happy to learn about it. With signed releases we could even publish vmd in the Mac App Store or Windows App Store.

**Comment by maxkueng** [comment]
@yoshuawuyts To create a new release, first update the version in `package.json` and create a tag and push, and then `npm publish`. Basically same as usual.  
Then `npm run package` to create the builds and then `npm run release` to create and upload the archives and publish the release.

`npm run package` [requires Wine](https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms) in order to put the icon in the Windows .exe.

`npm run release` requires a GitHub Remote Access Token to be in the `GITHUB_ACCESS_TOKEN` environment variable.

**Comment by yoshuawuyts** [comment]
@maxkueng madddd! Thanks so much for this :sparkles:
