### ISSUE TITLE
Missing background on Highlight.js themes

### ISSUE THREAD

**Issue by eush77** [yoshuawuyts/vmd#76]
For most Highlight.js themes background is pretty much part of the theme. However, background is currently missing with `vmd`.

![npm v browserify readme |vmd --highlight-theme=solarized-dark](https://cloud.githubusercontent.com/assets/4472489/13373570/1cde6b8a-dd7c-11e5-80d7-8c1d84dcf87f.png "Solarized Dark without background")

should be:

![previous + ad-hoc hacks](https://cloud.githubusercontent.com/assets/4472489/13373571/1cdebbee-dd7c-11e5-909b-6b237914d030.png "Solarized Dark with background")

Some themes are really ugly without a proper background:

![npm v browserify readme |vmd --highlight-theme=far](https://cloud.githubusercontent.com/assets/4472489/13373639/01a276f2-dd7e-11e5-99e5-427614f5f514.png "Far without background")

Fixing this issue requires [applying a `hljs` class](https://github.com/isagalaev/highlight.js/blob/80d5b7299dc8cedc8901e03bdad2b752341cc344/src/styles/solarized-dark.css#L7-L13) on `pre` element or containing `div`. Unfortunately, it isn't that simple because of [a higher-specificity rule](https://github.com/sindresorhus/github-markdown-css/blob/033e86abcb007c3f103b33324945f5ce845617cf/github-markdown.css#L477-L484) in `github-markdown-css`. I don't really know how to solve that. Any ideas?

**Comment by maxkueng** [comment]
Thanks for reporting this!

I found a solution and made a pull request (#78). IMO it's not the prettiest fix but it solves the problem.

 - I've added the `hljs` class to the `<pre>` tags in code blocks (bf66c3a)
 - and then made every CSS definition in the theme `!important` so that it overrules the higher-specificity rule from the GitHub styles (91acea5)

I haven't merged this yet as I have only tested it with the Solarized themes. I'd be glad if you could try it out and see if it works for you now and leave some feedback. Just pull the branch.
