### ISSUE TITLE
PintaProject/Pinta readme titles are not rendered well

### ISSUE THREAD

**Issue by averissimo** [yoshuawuyts/vmd#90]
From PintaProject/Pinta

![image](https://cloud.githubusercontent.com/assets/211358/18995754/8168bb66-8725-11e6-83e8-263dc102a17a.png)

**Comment by maxkueng** [comment]
Thanks for reporting this. It looks like the problem is that Pinta doesn't use a space after the `#` character which is required according to the [Markdown docs](https://daringfireball.net/projects/markdown/basics).

So 

```
#Pinta
```

should be

```
# Pinta
```

I tried a different markdown renderer and it behaves the same as "marked", which is what we're currently using. But since GitHub renders the headings in Pinta's readme even without the space I guess we should fix it.

**Comment by maxkueng** [comment]
vmd@1.28.0 is available on npm and supports headings without a space after the `#` characters. However, I'd recommend that you change the headings in Pinta's readme to include the spaces. Both John Gruber's markdown docs and [CommonMark specs](http://spec.commonmark.org/0.26/#atx-headings) require a space after the `#` sequence. CommonMark even explicitly mentions that the space is required.

From the CommonMark spec:

> An ATX heading consists of a string of characters, parsed as inline content, between an opening sequence of 1–6 unescaped `#` characters and an optional closing sequence of any number of unescaped `#` characters. **The opening sequence of `#` characters must be followed by a space** or by the end of line.

**Comment by averissimo** [comment]
I'm not a developer of Pinta, but i'l post a pr to change it :)

It was just really unlucky as I was using vmd for the first time to remember how to build it and it had this very minor problem, but as it was different from github's rendering I posted it.

Thanks for the fix, and it is a really useful tool

**Comment by maxkueng** [comment]
We try to render Markdown in vmd as closely as possible to how it's rendered on GitHub so it's good you found the problem. 

Thanks again
